name: mind_mate
description: A mental wellness app for students

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  flutter_svg: ^2.0.10
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  lottie: ^2.7.0
  url_launcher: ^6.3.2
  fluttertoast: ^8.2.2

flutter:
  assets:
    - assets/meditation.gif

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
